-- +goose Up
ALTER TABLE tests
ADD COLUMN target_url TEXT NOT NULL DEFAULT '',
ADD COLUMN method TEXT NOT NULL DEFAULT 'GET',
ADD COLUMN duration_sec INTEGER NOT NULL DEFAULT 30,
ADD COLUMN rps INTEGER NOT NULL DEFAULT 100,
ADD COLUMN concurrency INTEGER NOT NULL DEFAULT 10;

-- +goose Down
ALTER TABLE tests
DROP COLUMN concurrency,
DROP COLUMN rps,
DROP COLUMN duration_sec,
DROP COLUMN method,
DROP COLUMN target_url;
